### ISSUE TITLE
Can't write unknown attribute `invited_by_id'

### ISSUE THREAD

**Issue by leejarvis** [scambra/devise_invitable#336]
I'm seeing this issue on a production only environment. It works fine in development. This happens when I use `User.invite!(email: "foo@bar.com")`.

Facts:
- Rails version 4.0.0
- Ruby version 2.0.0
- Devise Invitible pointing at the `rails4` branch on GitHub, updated to `1c6a50bb29f8`.

Backtrace:

```
Loading production environment (Rails 4.0.0)
irb(main):001:0> User.invite!(email: 'foo@bar.com')
ActiveModel::MissingAttributeError: can't write unknown attribute `invited_by_id'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods/write.rb:45:in `write_attribute'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods/dirty.rb:70:in `write_attribute'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/attribute_methods.rb:317:in `[]='
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/associations/belongs_to_association.rb:64:in `replace_keys'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/associations/belongs_to_polymorphic_association.rb:13:in `replace_keys'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/associations/belongs_to_association.rb:14:in `replace'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/associations/singular_association.rb:17:in `writer'
    from /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.0.0/lib/active_record/associations/builder/association.rb:78:in `invited_by='
    from /app/vendor/bundle/ruby/2.0.0/bundler/gems/devise_invitable-1c6a50bb29f8/lib/devise_invitable/model.rb:237:in `_invite'
    from /app/vendor/bundle/ruby/2.0.0/bundler/gems/devise_invitable-1c6a50bb29f8/lib/devise_invitable/model.rb:257:in `invite!'
    from (irb):1
    from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
    from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Am I missing something?

**Comment by cosydney** [comment]
It's not noize I was faced with same issue 👍

**Comment by JCBoptimumweb** [comment]
as was I, so that helped. thank you @leejarvis

**Comment by zinkkrysty** [comment]
Had the same issue. Apparently I should restart the server after running migrations to make it work.

**Comment by scambra** [comment]
If you're in production, you must restart server after any change to code or db (that's how rails work, caching classes in production), development should get changes on every request.
