### ISSUE TITLE
authenticate_inviter! is throwing a wrong number of arguments error

### ISSUE THREAD

**Issue by marcamillion** [scambra/devise_invitable#609]
I am using:

```
    devise (3.2.4)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise_invitable (1.3.6)
      actionmailer (>= 3.2.6, < 5)
      devise (>= 3.2.0)
```

This is what my `create` action of my `Users::InvitationsController < Devise::InvitationsController` looks like:

```
    def create
      @member ||= Member.find_or_create_by(email: params[:user][:email], first_name: get_first_name(params[:user][:full_name]), last_name: get_last_name(params[:user][:full_name]), bio: params[:user][:bio], gender: params[:user][:gender])
      @membership ||= Membership.find_or_create_by(member: @member, family_tree: current_user.family_tree, inviter: current_user, relation: params[:user][:invitation_relation])

      if @user_exists ||= invited_user_exists(params[:email])

      else
        self.resource = invite_resource
        resource_invited = resource.errors.empty?

        yield resource if block_given?

        if resource_invited
          if is_flashing_format? && self.resource.invitation_sent_at
            set_flash_message :notice, :send_instructions, :email => self.resource.email
          end
          redirect_to root_path, notice: "Invitation Successfully Sent."
          # redirect_to post_url(@post), status: :found, notice: "Pay attention to the road"
        else
          respond_with_navigational(resource) { render :new }
        end
      end

    end
```

Whenever I try to invite a legit person that passes all the validations, this is the error I get:

```
Started POST "/users/invitation" for 127.0.0.1 at 2015-12-04 06:17:06 -0500
Processing by Users::InvitationsController#create as HTML
  Parameters: {"utf8"=>"✓", "user"=>{"full_name"=>"Random User", "email"=>"def@test.com", "gender"=>"female", "invitation_relation"=>"husband"}, "commit"=>"Send Invitation"}
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)

ArgumentError - wrong number of arguments (1 for 0):
  devise_invitable (1.3.6) lib/devise_invitable/controllers/helpers.rb:18:in `authenticate_inviter!'
  devise_invitable (1.3.6) app/controllers/devise/invitations_controller.rb:68:in `current_inviter'
  devise_invitable (1.3.6) app/controllers/devise/invitations_controller.rb:72:in `has_invitations_left?'
  activesupport (4.1.14) lib/active_support/callbacks.rb:429:in `block in make_lambda'
  activesupport (4.1.14) lib/active_support/callbacks.rb:143:in `block in halting_and_conditional'
  activesupport (4.1.14) lib/active_support/callbacks.rb:501:in `block in call'
  activesupport (4.1.14) lib/active_support/callbacks.rb:501:in `call'
  activesupport (4.1.14) lib/active_support/callbacks.rb:86:in `run_callbacks'
  actionpack (4.1.14) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.1.14) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.1.14) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.1.14) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.1.14) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.14) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.1.14) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.1.14) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.1.14) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.1.14) lib/abstract_controller/base.rb:136:in `process'
  actionview (4.1.14) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (0.9.3) lib/mini_profiler/profiling_methods.rb:106:in `block in profile_method'
  actionpack (4.1.14) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.1.14) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.1.14) lib/action_controller/metal.rb:232:in `block in action'
  actionpack (4.1.14) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
  actionpack (4.1.14) lib/action_dispatch/routing/route_set.rb:50:in `call'
  actionpack (4.1.14) lib/action_dispatch/routing/mapper.rb:45:in `call'
  actionpack (4.1.14) lib/action_dispatch/journey/router.rb:73:in `block in call'
  actionpack (4.1.14) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.1.14) lib/action_dispatch/routing/route_set.rb:692:in `call'
  jquery-fileupload-rails (0.4.5) lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
  jquery-fileupload-rails (0.4.5) lib/jquery/fileupload/rails/middleware.rb:10:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/cookies.rb:562:in `call'
  activerecord (4.1.14) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.14) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.14) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.14) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.14) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.14) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.14) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.14) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.14) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.14) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.14) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.1.14) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.14) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.14) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  rack-mini-profiler (0.9.3) lib/mini_profiler/profiler.rb:276:in `call'
  railties (4.1.14) lib/rails/engine.rb:514:in `call'
  railties (4.1.14) lib/rails/application.rb:144:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.5) lib/rack/server.rb:264:in `start'
  railties (4.1.14) lib/rails/commands/server.rb:69:in `start'
  railties (4.1.14) lib/rails/commands/commands_tasks.rb:81:in `block in server'
  railties (4.1.14) lib/rails/commands/commands_tasks.rb:76:in `server'
  railties (4.1.14) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
  railties (4.1.14) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'
```

This has just started happening since I customized my `create` action. It used to look like this:

```
    def create
      @member ||= Member.find_or_create_by(email: params[:user][:email], first_name: get_first_name(params[:user][:full_name]), last_name: get_last_name(params[:user][:full_name]), bio: params[:user][:bio], gender: params[:user][:gender])
      @membership ||= Membership.find_or_create_by(member: @member, family_tree: current_user.family_tree, inviter: current_user, relation: params[:user][:invitation_relation])

      if @user_exists ||= invited_user_exists(params[:email])
      else
        super
      end

    end
```

I changed it to the above version because the redirect wasn't working - even if I overrode `after_invite_path_for(resource)` in my local controller. It still wouldn't redirect properly.

Either way, now that I have basically copied/pasted the actual `create` code into my `create` it is now giving me this error.

Thoughts?

**Comment by marcamillion** [comment]
I just removed the snippet within the `else` block of the `if` statement in the `create` action and reverted it to `super` and it is still generating this error - so it seems it must be something else.

What could be causing this?

**Comment by marcamillion** [comment]
Ok I figured this out. 

I had recently added an `authorize_user!` method to my `applications_controller` to fix another issue and it caused this one. Once I took that out, this issue no longer showed itself.
