### ISSUE TITLE
devise_invitable not working with rails 5 alpha

### ISSUE THREAD

**Issue by ecleel** [scambra/devise_invitable#611]
I'm building an API using rails 5 alpha and when I try to run comand ```rails generate devise_invitable:install``` this error raised

```
/Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable/controllers/helpers.rb:5:in `block in <module:Helpers>': undefined method `hide_action' for ActionController::Base:Class (NoMethodError)
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/concern.rb:120:in `class_eval'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/concern.rb:120:in `append_features'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable/rails.rb:5:in `include'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable/rails.rb:5:in `block in <class:Engine>'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable/rails.rb:4:in `<class:Engine>'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable/rails.rb:2:in `<module:DeviseInvitable>'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable/rails.rb:1:in `<top (required)>'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/dependencies.rb:302:in `block in require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-32a8cd961eec/activesupport/lib/active_support/dependencies.rb:302:in `require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise_invitable-1.5.3/lib/devise_invitable.rb:14:in `<top (required)>'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/ecleel/codes/moyasar/api/config/application.rb:16:in `<top (required)>'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `require'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:82:in `preload'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:143:in `serve'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /Users/ecleel/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
```

Any idea how to fix this problem?
Thank you

**Comment by ecleel** [comment]
I think Rails folks remove (hide_action)[https://github.com/rails/rails/issues/18336]. I'll be happy to create a pull request to fix the problem.
