### ISSUE TITLE
Devise 4.0 compatibility

### ISSUE THREAD

**Issue by tagliala** [scambra/devise_invitable#645]
Using Ruby 2.3.0, Rails 4.2.6, Devise 4

```
$ rails s
~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method': undefined method `attributes_for' for class `Devise::ParameterSanitizer' (NameError)
Did you mean?  attr_writer
	from ~/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/module/aliasing.rb:32:in `alias_method_chain'
	from ~/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.5.5/lib/devise_invitable/parameter_sanitizer.rb:12:in `included'
	from ~/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.5.5/lib/devise_invitable/rails.rb:20:in `include'
	from ~/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.5.5/lib/devise_invitable/rails.rb:20:in `block in <class:Engine>'
```

Devise changed something about Parameter Sanitizer, you can take a look at the [changelog](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#400rc1---2016-01-02)

**Comment by scambra** [comment]
It was fixed in master, I will release new version soon

**Comment by tagliala** [comment]
Thanks! All my specs pass with 4.6.0 👍

**Comment by ChunAllen** [comment]
@scambra when would be the release of the support for Devise 4.0+ ?

**Comment by scambra** [comment]
1.6.0 supports devise 4.0 and it was released weeks ago
