### ISSUE TITLE
devise-async + devise_invitable not working (ArgumentError: wrong number of arguments (given 3, expected 1..2))

### ISSUE THREAD

**Issue by LeKristapino** [scambra/devise_invitable#661]
`User.invite!(email: "test@test.com")`

produces 

```
ArgumentError: wrong number of arguments (given 3, expected 1..2)
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/devise-async-0.7.0/lib/devise/async/model.rb:27:in `send_devise_notification'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.6.0/lib/devise_invitable/model.rb:193:in `deliver_invitation'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.6.0/lib/devise_invitable/model.rb:151:in `block in invite!'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:750:in `_run_invitation_created_callbacks'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.0/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.6.0/lib/devise_invitable/model.rb:140:in `invite!'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.6.0/lib/devise_invitable/model.rb:302:in `_invite'
	from /Users/Kristaps/.rvm/gems/ruby-2.3.0/gems/devise_invitable-1.6.0/lib/devise_invitable/model.rb:307:in `invite!'
```

**Comment by scambra** [comment]
You need to udpate devise-async, not only devise invitable is using 3 arguments, other devise modules use 3 args too.
