### ISSUE TITLE
Socket Error assigning invited user to a project

### ISSUE THREAD

**Issue by JorgeATR** [scambra/devise_invitable#717]
My app has a Project model, an admin can create many projects and invite users to any of them. Any account created with Devise registrations/sign_up has admin: true, it defaults to false therefor all invited users are not admins. When I invite a new user and select the Project I want to assign it to I get the following error (more details in the trace below):

> SocketError in Users::InvitationsController#create 
> getaddrinfo: Name or service not known
> 
>     def tcp_socket(address, port)
>       TCPSocket.open address, port
>     end

The weird thing is that the invited user is created (as seen below in the trace). I've found some slightly unrelated answers that say that this is because the hostname can't be resolved to an IP address, hence this line in my environments/development.rb:
`config.action_mailer.default_url_options = { :host => "localhost:3000" }  `

```
# InvitationsController
 def invite_resource!
    super do |user|
      project = Project.find_by(id: params[:user][:project_ids])
      user.projects << project if project
    end
  end
```
```
# routes
devise_for :users, controllers: { registrations: 'users/registrations',
                                                  invitations: 'users/invitations' }
```

```
web_1          | app/controllers/users/invitations_controller.rb:8:in `invite_resource'
web_1          | Started GET "/users/invitation/new" for 172.21.0.1 at 2017-09-26 22:14:34 +0000
web_1          | Cannot render console from 172.21.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1          | Processing by Users::InvitationsController#new as HTML
web_1          |   User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
web_1          |   Rendering devise/invitations/new.html.erb within layouts/application
web_1          |   Project Load (0.3ms)  SELECT "projects".* FROM "projects"
web_1          |   User Load (0.6ms)  SELECT "users".* FROM "users" WHERE ("users"."invitation_sent_at" IS NOT NULL)
web_1          |   Rendered devise/invitations/new.html.erb within layouts/application (29.1ms)
web_1          |   Rendered application/_header.html.erb (3.5ms)
web_1          | Completed 200 OK in 115ms (Views: 81.0ms | ActiveRecord: 6.8ms)
web_1          | 
web_1          | 
web_1          | Started POST "/users/invitation" for 172.21.0.1 at 2017-09-26 22:14:48 +0000
web_1          | Cannot render console from 172.21.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
web_1          | Processing by Users::InvitationsController#create as HTML
web_1          |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"wfcE48FqDpuGxfOxNSSkAfqfDyIKEr69w188Gb83c4xmv4qm/OaqiugbZZqYdjdygQqyHUMXDctNf15frsvx6w==", "user"=>{"email"=>"wabroni@test.com", "project_ids"=>"1"}, "commit"=>"Send an invitation"}
web_1          |   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
web_1          |   User Load (0.7ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "wabroni@test.com"], ["LIMIT", 1]]
web_1          |   Project Load (0.4ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = 1
web_1          |   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."invitation_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["invitation_token", "5b3d7586103a65f00ba24364415a0720de961fe0c764d0f5a3d0c9cf73f86eee"], ["LIMIT", 1]]
web_1          |    (0.2ms)  BEGIN
web_1          |   SQL (0.5ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "invitation_token", "invitation_created_at", "invitation_sent_at", "invited_by_type", "invited_by_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"  [["email", "wabroni@test.com"], ["encrypted_password", "$2a$11$SqgVGDsVdAV0JvY17n4hTOvPvl/gZD5DRwZ7mXdUOwu45uVNvDZrC"], ["created_at", "2017-09-26 22:14:48.448414"], ["updated_at", "2017-09-26 22:14:48.448414"], ["invitation_token", "5b3d7586103a65f00ba24364415a0720de961fe0c764d0f5a3d0c9cf73f86eee"], ["invitation_created_at", "2017-09-26 22:14:48.447438"], ["invitation_sent_at", "2017-09-26 22:14:48.447438"], ["invited_by_type", "User"], ["invited_by_id", 1]]
web_1          |   SQL (0.9ms)  INSERT INTO "user_projects" ("user_id", "project_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["user_id", 4], ["project_id", 1], ["created_at", "2017-09-26 22:14:48.450560"], ["updated_at", "2017-09-26 22:14:48.450560"]]
web_1          |    (0.9ms)  COMMIT
web_1          |   Rendering devise/mailer/invitation_instructions.html.erb
web_1          |   Rendered devise/mailer/invitation_instructions.html.erb (1.8ms)
web_1          |   Rendering devise/mailer/invitation_instructions.text.erb
web_1          |   Rendered devise/mailer/invitation_instructions.text.erb (2.2ms)
web_1          | Devise::Mailer#invitation_instructions: processed outbound mail in 16.7ms
web_1          | Sent mail to wabroni@test.com (20015.7ms)
web_1          | Date: Tue, 26 Sep 2017 22:14:48 +0000
web_1          | From: "temp@email.com" localhost:3000
web_1          | Reply-To: "temp@email.com" localhost:3000
web_1          | To: wabroni@test.com
web_1          | Message-ID: <59cad158735b0_123c1098823b0@96da2342fb59.mail>
web_1          | Subject: Invitation instructions
web_1          | Mime-Version: 1.0
web_1          | Content-Type: multipart/alternative;
web_1          |  boundary="--==_mimepart_59cad15872886_123c1098822eb";
web_1          |  charset=UTF-8
web_1          | Content-Transfer-Encoding: 7bit
web_1          | 
web_1          | 
web_1          | ----==_mimepart_59cad15872886_123c1098822eb
web_1          | Content-Type: text/plain;
web_1          |  charset=UTF-8
web_1          | Content-Transfer-Encoding: 7bit
web_1          | 
web_1          | Hello wabroni@test.com
web_1          | 
web_1          | Someone has invited you to http://localhost:3000/, you can accept it through the link below.
web_1          | 
web_1          | http://localhost:3000/users/invitation/accept?invitation_token=Jcd3KyyzT_wqCGxGbBDy
web_1          | 
web_1          |   This invitation will be due in October 24, 2017 10:14 PM.
web_1          | 
web_1          | If you don't want to accept the invitation, please ignore this email.
web_1          | Your account won't be created until you access the link above and set your password.
web_1          | 
web_1          | ----==_mimepart_59cad15872886_123c1098822eb
web_1          | Content-Type: text/html;
web_1          |  charset=UTF-8
web_1          | Content-Transfer-Encoding: 7bit
web_1          | 
web_1          | <div style="background-color: whitesmoke; padding: 70px; text-align: center;">
web_1          |   <p style="color: #9b9b9b; font-weight: bold;">Hello wabroni@test.com</p>
web_1          |   <p style="color: #9b9b9b; ">Someone has invited you to http://localhost:3000/, you can accept it through the link below.</p>
web_1          |   <div style="margin: 20px 0; text-align: center;">
web_1          |     <p style="background-color: #18b5f9; border: 0; border-radius: 4px; color: #fff; cursor: pointer; display: inline-block; padding: 14px 20px;"><a href="http://localhost:3000/users/invitation/accept?invitation_token=Jcd3KyyzT_wqCGxGbBDy">Accept invitation</a></p>
web_1          |   </div>
web_1          |     <p style="font-style: italic;">This invitation will be due in October 24, 2017 10:14 PM.</p>
web_1          |   <p>If you don't want to accept the invitation, please ignore this email.<br />
web_1          | Your account won't be created until you access the link above and set your password.</p>
web_1          | </div>
web_1          | 
web_1          | ----==_mimepart_59cad15872886_123c1098822eb--
web_1          | 
web_1          | Completed 500 Internal Server Error in 20196ms (ActiveRecord: 8.1ms)
web_1          | 
web_1          | 
web_1          |   
web_1          | SocketError (getaddrinfo: Name or service not known):
web_1          |   
web_1          | /usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
web_1          | /usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `open'
web_1          | /usr/local/lib/ruby/2.4.0/net/smtp.rb:539:in `tcp_socket'
web_1          | /usr/local/lib/ruby/2.4.0/net/smtp.rb:549:in `block in do_start'
web_1          | /usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
web_1          | /usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
web_1          | /usr/local/lib/ruby/2.4.0/net/smtp.rb:548:in `do_start'
web_1          | /usr/local/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
web_1          | mail (2.6.6) lib/mail/network/delivery_methods/smtp.rb:111:in `deliver!'
web_1          | mail (2.6.6) lib/mail/message.rb:2149:in `do_delivery'
web_1          | mail (2.6.6) lib/mail/message.rb:237:in `block in deliver'
web_1          | actionmailer (5.1.3) lib/action_mailer/base.rb:558:in `block in deliver_mail'
web_1          | activesupport (5.1.3) lib/active_support/notifications.rb:166:in `block in instrument'
web_1          | activesupport (5.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
web_1          | activesupport (5.1.3) lib/active_support/notifications.rb:166:in `instrument'
web_1          | actionmailer (5.1.3) lib/action_mailer/base.rb:556:in `deliver_mail'
web_1          | mail (2.6.6) lib/mail/message.rb:237:in `deliver'
web_1          | actionmailer (5.1.3) lib/action_mailer/message_delivery.rb:96:in `block in deliver_now'
web_1          | actionmailer (5.1.3) lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
web_1          | actionmailer (5.1.3) lib/action_mailer/message_delivery.rb:95:in `deliver_now'
web_1          | devise (4.3.0) lib/devise/models/authenticatable.rb:191:in `send_devise_notification'
web_1          | devise_invitable (1.7.2) lib/devise_invitable/model.rb:195:in `deliver_invitation'
web_1          | devise_invitable (1.7.2) lib/devise_invitable/model.rb:153:in `block in invite!'
web_1          | activesupport (5.1.3) lib/active_support/callbacks.rb:97:in `run_callbacks'
web_1          | devise_invitable (1.7.2) lib/devise_invitable/model.rb:142:in `invite!'
web_1          | devise_invitable (1.7.2) lib/devise_invitable/model.rb:304:in `_invite'
web_1          | devise_invitable (1.7.2) lib/devise_invitable/model.rb:310:in `invite!'
web_1          | devise_invitable (1.7.2) app/controllers/devise/invitations_controller.rb:87:in `invite_resource'
web_1          | devise_invitable (1.7.2) app/controllers/devise/invitations_controller.rb:26:in `create'
web_1          | actionpack (5.1.3) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
web_1          | actionpack (5.1.3) lib/abstract_controller/base.rb:186:in `process_action'
web_1          | actionpack (5.1.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
web_1          | actionpack (5.1.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
web_1          | activesupport (5.1.3) lib/active_support/callbacks.rb:131:in `run_callbacks'
web_1          | actionpack (5.1.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
web_1          | actionpack (5.1.3) lib/action_controller/metal/rescue.rb:20:in `process_action'
web_1          | actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
web_1          | activesupport (5.1.3) lib/active_support/notifications.rb:166:in `block in instrument'
web_1          | activesupport (5.1.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
web_1          | activesupport (5.1.3) lib/active_support/notifications.rb:166:in `instrument'
web_1          | actionpack (5.1.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
web_1          | actionpack (5.1.3) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
web_1          | activerecord (5.1.3) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
web_1          | actionpack (5.1.3) lib/abstract_controller/base.rb:124:in `process'
web_1          | actionview (5.1.3) lib/action_view/rendering.rb:30:in `process'
web_1          | actionpack (5.1.3) lib/action_controller/metal.rb:189:in `dispatch'
web_1          | actionpack (5.1.3) lib/action_controller/metal.rb:253:in `dispatch'
web_1          | actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
web_1          | actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:31:in `serve'
web_1          | actionpack (5.1.3) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
web_1          | actionpack (5.1.3) lib/action_dispatch/routing/mapper.rb:46:in `serve'
web_1          | actionpack (5.1.3) lib/action_dispatch/journey/router.rb:46:in `block in serve'
web_1          | actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `each'
web_1          | actionpack (5.1.3) lib/action_dispatch/journey/router.rb:33:in `serve'
web_1          | actionpack (5.1.3) lib/action_dispatch/routing/route_set.rb:834:in `call'
web_1          | warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
web_1          | warden (1.2.7) lib/warden/manager.rb:35:in `catch'
web_1          | warden (1.2.7) lib/warden/manager.rb:35:in `call'
web_1          | rack (2.0.3) lib/rack/etag.rb:25:in `call'
web_1          | rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
web_1          | rack (2.0.3) lib/rack/head.rb:12:in `call'
web_1          | rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context'
web_1          | rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/cookies.rb:613:in `call'
web_1          | activerecord (5.1.3) lib/active_record/migration.rb:556:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
web_1          | activesupport (5.1.3) lib/active_support/callbacks.rb:97:in `run_callbacks'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web_1          | web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web_1          | web-console (3.5.1) lib/web_console/middleware.rb:20:in `block in call'
web_1          | web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web_1          | web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
web_1          | railties (5.1.3) lib/rails/rack/logger.rb:36:in `call_app'
web_1          | railties (5.1.3) lib/rails/rack/logger.rb:24:in `block in call'
web_1          | activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
web_1          | activesupport (5.1.3) lib/active_support/tagged_logging.rb:26:in `tagged'
web_1          | activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `tagged'
web_1          | railties (5.1.3) lib/rails/rack/logger.rb:24:in `call'
web_1          | sprockets-rails (3.2.0) lib/sprockets/rails/quiet_assets.rb:13:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/request_id.rb:25:in `call'
web_1          | rack (2.0.3) lib/rack/method_override.rb:22:in `call'
web_1          | rack (2.0.3) lib/rack/runtime.rb:22:in `call'
web_1          | activesupport (5.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
web_1          | actionpack (5.1.3) lib/action_dispatch/middleware/static.rb:125:in `call'
web_1          | rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
web_1          | railties (5.1.3) lib/rails/engine.rb:522:in `call'
web_1          | puma (3.10.0) lib/puma/configuration.rb:225:in `call'
web_1          | puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
web_1          | puma (3.10.0) lib/puma/server.rb:437:in `process_client'
web_1          | puma (3.10.0) lib/puma/server.rb:301:in `block in run'
web_1          | puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by scambra** [comment]
Right, hostname can't be resolved to an IP address, not default_url_options, which are used to render url links and rails won't try to connect, but hostname in action_mailer settings.

However, it isn't a devise invitable bug, and not related to devise invitable.
You have some issue to deliver emails from rails. Please, ask in any rails forum, or devise user group.
