### ISSUE TITLE
The migration generator creates an unsupported migration because it does not specify the Rails version

### ISSUE THREAD

**Issue by stephenhmarsh** [scambra/devise_invitable#738]
On Rails 5.1.5.rc1

Running `bundle exec rails db:migrate` blows up with:

```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class DeviseInvitableAddToUsers < ActiveRecord::Migration[4.2]
```

Full trace:

```
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:525:in `inherited'
/Users/stephen/dev/group-project/db/migrate/20180209083920_devise_invitable_add_to_users.rb:1:in `<top (required)>'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5.rc1/lib/active_support/dependencies.rb:292:in `require'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5.rc1/lib/active_support/dependencies.rb:292:in `block in require'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5.rc1/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5.rc1/lib/active_support/dependencies.rb:292:in `require'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:962:in `load_migration'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:958:in `migration'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:953:in `disable_ddl_transaction'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1305:in `use_transaction?'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1297:in `ddl_transaction'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1229:in `execute_migration_in_transaction'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1201:in `block in migrate_without_lock'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1200:in `each'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1200:in `migrate_without_lock'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1148:in `block in migrate'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1317:in `with_advisory_lock'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1148:in `migrate'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:1007:in `up'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/migration.rb:985:in `migrate'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5.rc1/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5.rc1/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5.rc1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5.rc1/lib/rails/command.rb:46:in `invoke'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5.rc1/lib/rails/commands.rb:16:in `<top (required)>'
/Users/stephen/dev/group-project/bin/rails:9:in `require'
/Users/stephen/dev/group-project/bin/rails:9:in `<top (required)>'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/stephen/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/stephen/dev/group-project/bin/spring:15:in `require'
/Users/stephen/dev/group-project/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

```

I fixed this by changing:
```class DeviseInvitableAddToUsers < ActiveRecord::Migration```
to:
```class DeviseInvitableAddToUsers < ActiveRecord::Migration[5.1]```
At the top of the generated migration file.

**Comment by scambra** [comment]
1.7.3 was released at Feb 9th.
