### ISSUE TITLE
undefined method `persisted?' during User.invite!(user_params)

### ISSUE THREAD

**Issue by KirillMachuhin** [scambra/devise_invitable#755]
Hi folks. Faced with problem after generating project with **Rails 5 in api mode.**
Namely I created custom invitation controller and extend it with _'Devise::Models::Invitable'_ and try to use _'invite!'_ method for User model.
Unfortunately I got an error **_undefined method `persisted?'_** in _invited_to_sign_up?_ method (as I understood) and here self object is User but without params.

Could you help me with implementation?

**Comment by scambra** [comment]
Devise::Models::Invitable must be included in a model, not controller. Indeed, instead of include that module, you should add :invitable to devise line in your model.

**Comment by scambra** [comment]
Can you post your devise line?

**Comment by KirillMachuhin** [comment]
`devise :invitable, :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable`

**Comment by scambra** [comment]
Run rake --trace routes to see where is calling arity on a hash

**Comment by KirillMachuhin** [comment]
```
** Invoke routes (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `arity' for {:polymorphic=>true, :optional=>true}:Hash
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:51:in `build_scope'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:43:in `create_reflection'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations/builder/association.rb:31:in `build'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/associations.rb:1654:in `belongs_to'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/acts_as_paranoid-d643738e1373/lib/acts_as_paranoid/associations.rb:14:in `belongs_to_with_deleted'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise_invitable-1.7.4/lib/devise_invitable/models.rb:48:in `block in <module:Invitable>'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/concern.rb:122:in `class_eval'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/concern.rb:122:in `append_features'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/models.rb:104:in `include'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/models.rb:104:in `block (2 levels) in devise'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/models.rb:89:in `each'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/models.rb:89:in `block in devise'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/models.rb:115:in `devise_modules_hook!'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/devise-4.4.3/lib/devise/models.rb:86:in `devise'
/Users/kirill.machukhin/projects/my_api/osbb/app/models/user.rb:12:in `<class:User>'
/Users/kirill.machukhin/projects/my_api/osbb/app/models/user.rb:3:in `<main>'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:100:in `load'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:468:in `block in load_file'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:653:in `new_constants_in'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:467:in `load_file'
/Users/kirill.machukhin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:365:in `block in require_or_load'
```

**Comment by scambra** [comment]
I see you are using rails 5.2, I have added tests for rails 5.2 and they work.
Also, I see acts_as_paranoid overrides belongs_to, can you test it without acts_as_paranoid, to see if error is caused by devise invitable or acts_as_paranoid?

**Comment by KirillMachuhin** [comment]
OMG! You was right. The problem in acts_as_paranoid gem... Thank you for your attention

**Comment by scambra** [comment]
I think they have bug because belongs_to signature changed in rails 5.2, from:
```def belongs_to(name, scope = nil, options = {})```
to:
```def belongs_to(name, scope = nil, **options)```

Then rails 5.2 doesn't check scope.is_a? Hash
