### ISSUE TITLE
No Method Error when running automatic install

### ISSUE THREAD

**Issue by PatrickatPaperlessPCS** [scambra/devise_invitable#880]
Working on a new install.  Added to gemfile, bundle install without error, devise_invitable 2.0.6 installed successfully.

Ran `rails generate devise_invitable:install`  and ran into this error:

```
/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:589:in `method_missing': undefined method `raise_credential_errors=' for ActionMailer::Base:Class
Did you mean?  raise_delivery_errors= (NoMethodError)
```

Ran bundle update just in case actionmailer was out of date.  Was running actionmailer 6.1.5 on initial attempt, 6.1.7 installed with update but had the same result when running devise_invitable:install again.

**Comment by PatrickatPaperlessPCS** [comment]
Ran into the same error when trying to [manually install](https://github.com/scambra/devise_invitable#manual-installation-)

**Comment by scambra** [comment]
Do you have a backtrace to see which line is calling that method? I don't see any reference to that method in the code of this gem

**Comment by PatrickatPaperlessPCS** [comment]
full output:  

```
/home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:589:in `method_missing': undefined method `raise_credential_errors=' for ActionMailer::Base:Class
Did you mean?  raise_delivery_errors= (NoMethodError)
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/railtie.rb:48:in `block (3 levels) in <class:Railtie>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/railtie.rb:48:in `each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/railtie.rb:48:in `block (2 levels) in <class:Railtie>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:51:in `each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:1029:in `<class:Base>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:437:in `<module:ActionMailer>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:12:in `<main>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:288:in `const_get'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:288:in `block in constantize'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `inject'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `constantize'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/devise-4.8.1/app/mailers/devise/mailer.rb:4:in `<main>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:27:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:288:in `const_get'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:288:in `block in constantize'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `inject'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/inflector/methods.rb:284:in `constantize'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:19:in `constantize'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/devise-4.8.1/lib/devise.rb:318:in `get'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/devise-4.8.1/lib/devise.rb:343:in `mailer'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/devise_invitable-2.0.6/lib/devise_invitable/rails.rb:12:in `block in <class:Engine>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	from /home/porchpoddev/code/deliverypoint/config/environment.rb:5:in `<main>'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `block in require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:332:in `require'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/spring-4.1.0/lib/spring/application.rb:107:in `preload'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/spring-4.1.0/lib/spring/application.rb:166:in `serve'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/spring-4.1.0/lib/spring/application.rb:148:in `block in run'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/spring-4.1.0/lib/spring/application.rb:142:in `loop'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/spring-4.1.0/lib/spring/application.rb:142:in `run'
	from /home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/spring-4.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/porchpoddev/.rbenv/versions/3.0.3/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'

```

**Comment by scambra** [comment]
There is no referencie to raise_delivery_errors in devise invitable. The line in the backtrace just include the helper in devise mailer.

ActionMailer::Railtie is getting options here
https://github.com/rails/rails/blob/v6.1.7/actionmailer/lib/action_mailer/railtie.rb#L19
From app.config.action_mailer, so I guess you have it in config environments, or some initializer.

**Comment by PatrickatPaperlessPCS** [comment]
@scambra confirmed that action_mailer was not set up properly, causing the issue.  Sorry about that, but thanks for the help!
