### ISSUE TITLE
Rails - Plan to support v7.2?

### ISSUE THREAD

**Issue by ewlarson** [scambra/devise_invitable#915]
Hi there! I've been a very happy user of this gem for years. Thanks for everything you've done for it.

A Rails engine I wrote uses devise and devise_invitable, but I'm seeing an error (see stack trace below) bubble up from devise_invitable when trying to test Rails 7.2 support while running test builds of my engine-based application. If I remove devise_invitable from my engine, everything builds as expected.

Rails 7.1 [deprecated](https://github.com/rails/rails/blob/de71ea80887d0d3dab979eac419f6f7cea956b51/guides/source/7_1_release_notes.md?plain=1#L637) `preview_path` and Rails 7.2 [removed](https://github.com/rails/rails/blob/de71ea80887d0d3dab979eac419f6f7cea956b51/guides/source/7_2_release_notes.md?plain=1#L397) `preview_path`.

Do you have plans to test 7.2 support? — I see only 7.0 in the test matrix.

Ruby v3.3 would also be nice to test. And, actually, looking closer at the test matrix I see a lot of End of Life [Rails](https://endoflife.date/rails)/[Ruby](https://endoflife.date/ruby) versions in the test matrix. Perhaps the matrix should be revised accordingly?

```
/Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/base.rb:632:in `method_missing': undefined method `preview_path=' for class ActionMailer::Base (NoMethodError)
Did you mean?  preview_paths=
               _view_paths=
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/railtie.rb:62:in `block (3 levels) in <class:Railtie>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/railtie.rb:62:in `each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/railtie.rb:62:in `block (2 levels) in <class:Railtie>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:97:in `class_eval'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:97:in `block in execute_hook'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:77:in `each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/base.rb:1074:in `<class:Base>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/base.rb:476:in `<module:ActionMailer>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/actionmailer-7.2.1/lib/action_mailer/base.rb:12:in `<top (required)>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/inflector/methods.rb:290:in `const_get'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/inflector/methods.rb:290:in `constantize'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/devise-4.9.4/app/mailers/devise/mailer.rb:4:in `<top (required)>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:26:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/inflector/methods.rb:290:in `const_get'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/inflector/methods.rb:290:in `constantize'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise.rb:327:in `get'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/devise-4.9.4/lib/devise.rb:350:in `mailer'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/devise_invitable-2.0.9/lib/devise_invitable/rails.rb:12:in `block in <class:Engine>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:407:in `instance_exec'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:407:in `block in make_lambda'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:179:in `block in call'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:668:in `block (2 levels) in default_terminator'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:667:in `catch'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:667:in `block in default_terminator'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:180:in `call'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `block in invoke_before'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:559:in `invoke_before'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/callbacks.rb:109:in `run_callbacks'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/activesupport-7.2.1/lib/active_support/reloader.rb:96:in `prepare!'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:32:in `run'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:350:in `each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:350:in `call'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/application.rb:435:in `initialize!'
	from /Users/ewlarson/Rails/geoblacklight_admin/.internal_test_app/config/environment.rb:5:in `<top (required)>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/application.rb:411:in `require_environment!'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/command/actions.rb:20:in `boot_application!'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/commands/generate/generate_command.rb:10:in `help'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/commands/generate/generate_command.rb:19:in `perform'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/command.rb:71:in `block in invoke'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/command.rb:149:in `with_argv'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/command.rb:69:in `invoke'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/railties-7.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
	from /Users/ewlarson/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from bin/rails:4:in `<main>'
```

**Comment by ewlarson** [comment]
Just a quick follow up here to say, my Rails 7.2 error appears to only arise when devise_invitable is included in my Rails Engine's generator install scripts.

**Comment by scambra** [comment]
There's no code in devise_invitable calling using preview_path, the only difference is that devise_invitable loads devise mailer on the initialization, and it inherits from Devise.parent_mailer.constantize, which is the call which triggers the error. I don't see preview_path in the devise gem either, so it must be in the class you're using as parent_mailer.

**Comment by scambra** [comment]
I have updated CI to test with rails 7.2 and tests are passing

**Comment by ewlarson** [comment]
Circling back here, in case anyone ends up puzzled like I was... I had an old rspec-rails gem in my project, which was the culprit. For more info see:
https://github.com/rspec/rspec-rails/issues/2703
